//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProyectosEntities : DbContext
    {
        public ProyectosEntities()
            : base("name=ProyectosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Compañia> Compañia { get; set; }
        public virtual DbSet<Historias> Historias { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<Tikets> Tikets { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<vw_ListaHistorias> vw_ListaHistorias { get; set; }
        public virtual DbSet<vw_ListaProyectos> vw_ListaProyectos { get; set; }
        public virtual DbSet<vw_ListaTikets> vw_ListaTikets { get; set; }
        public virtual DbSet<vw_ListaUsuarios> vw_ListaUsuarios { get; set; }
        public virtual DbSet<vw_ListaCompañias> vw_ListaCompañias { get; set; }
    
        public virtual int Sp_Usuario_Create(string nombre, string usuario, string contraseña)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Usuario_Create", nombreParameter, usuarioParameter, contraseñaParameter);
        }
    
        public virtual int Sp_Proyecto_Create(string nombre, string descripcion, string usuario, Nullable<System.DateTime> fechaCreacion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("FechaCreacion", fechaCreacion) :
                new ObjectParameter("FechaCreacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Proyecto_Create", nombreParameter, descripcionParameter, usuarioParameter, fechaCreacionParameter);
        }
    
        public virtual int Sp_Historias_Create(string nombre, string descripcion, string usuario, Nullable<System.DateTime> fechaCreacion, Nullable<int> rowIDProyecto)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("FechaCreacion", fechaCreacion) :
                new ObjectParameter("FechaCreacion", typeof(System.DateTime));
    
            var rowIDProyectoParameter = rowIDProyecto.HasValue ?
                new ObjectParameter("RowIDProyecto", rowIDProyecto) :
                new ObjectParameter("RowIDProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Historias_Create", nombreParameter, descripcionParameter, usuarioParameter, fechaCreacionParameter, rowIDProyectoParameter);
        }
    
        public virtual int Sp_Tikets_Create(string nombre, string descripcion, string estado, string activo, string usuario, Nullable<System.DateTime> fechaCreacion, Nullable<int> rowIDHistoria)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var activoParameter = activo != null ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("FechaCreacion", fechaCreacion) :
                new ObjectParameter("FechaCreacion", typeof(System.DateTime));
    
            var rowIDHistoriaParameter = rowIDHistoria.HasValue ?
                new ObjectParameter("RowIDHistoria", rowIDHistoria) :
                new ObjectParameter("RowIDHistoria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Tikets_Create", nombreParameter, descripcionParameter, estadoParameter, activoParameter, usuarioParameter, fechaCreacionParameter, rowIDHistoriaParameter);
        }
    }
}
